### ISSUE TITLE
ClassCastException loading model in Apache Spark

### ISSUE THREAD

**Issue by timcroydon** [dlwh/epic#17]
Hi there,

I'm trying to use epic in an Apache Spark Streaming environment but I'm experiencing some difficulty loading the models. I'm not really sure whether this is an Epic issue, a Breeze issue, a Spark issue or where/how to solve this now! I get the following exception (for English NER):

<pre><code>
Exception in thread "main" java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field epic.features.BrownClusterFeaturizer.epic$features$BrownClusterFeaturizer$$clusterFeatures of type scala.collection.immutable.Map in instance of epic.features.BrownClusterFeaturizer
    at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2083)
    at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1996)
    ... trimmed ...
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    at breeze.util.package$.readObject(package.scala:21)
    at epic.models.package$.deserialize(package.scala:54)
        ... trimmed calls from my code ...
</code></pre>

I've tried running my code (compiled into uberjar using 'sbt assembly') in a raw scala console and I can load the model and run it fine. However, using Spark, I get the exception described. The ONLY difference as far as I can tell is the way the model file is referenced.  For the raw scala environment, I can point directly at the model file on disk (e.g. `new File("mymodels/model.ser.gz")`) and it loads. In Spark, I have to load the file doing something similar to:

```
sc.addFile("model.ser.gz")
new File(SparkFiles.get("model.ser.gz")
```

I've tried narrowing the code down and depending whether I point at the model extracted from the jar or the jar itself I get the same result. It's definitely loading the file (I think) as it fails in other ways if the file doesn't exist. I even tried bypassing the Breeze `nonStupidObjectInputStream` to no avail.

Any idea what's going on or how to test? For reference, my JVM is 1.7.0_51 and same in both scala and Spark environments.

Thanks.

**Comment by JSantosP** [comment]
Hi there,

I just googled, looking for a solution for a similar problem in a project I'm working in, and we found and fixed the problem cause (I'm not sure if it fixes your current problem).

We solved it adding missing classpath dependencies when creating SparkContext (not only direct dependencies):
```
  val sparkConf = new SparkConf().setJars("...") //Add all transitive dependencies that Spark workers might need.
```

Hope this helps.

Regards!

**Comment by acvogel** [comment]
@timcroydon Any chance you found a solution to this problem? Running into the same issue.

**Comment by reactormonk** [comment]
@acvogel the solution @JSantosP provided doesn't work?

**Comment by timcroydon** [comment]
I don't recall now, I'm afraid. For various unrelated reasons, we ended up using a different library for similar functionality so I don't think I ever got round to investigating this fully - sorry!

**Comment by acvogel** [comment]
@reactormonk I haven't gotten it to work by that route, but perhaps I'm missing something. I assemble the project into a single jar, and also add dependent jars:

SparkConf().setJars(Seq("/root/myBigJar.jar", "/root/epic-ner-en-conll_2.10-2015.1.25.jar", "/root/epic_2.10-0.3.jar"))

Perhaps I'm missing not following  @JSantosP suggestion correctly, as those should be included in myBigJar.jar anyway.

@timcroydon Thanks for your reply!

**Comment by dlwh** [comment]
there's a jar from february that works, i believe. can't fix atm.

**Comment by briantopping** [comment]
I've been using the 2015.2.19 data files combined with the sources from https://github.com/dlwh/epic/tree/e0238ceb16fc9adb9511240638357e8c44200a2f. The files from February work, but I believe this branch is the last one that works. I covered some of it in https://github.com/dlwh/epic/issues/24 IIRC.

**Comment by loretofcostas** [comment]
I had the same problem and the  JSantosP solutioin worked for me. Thank you.

**Comment by ltao80** [comment]
What is the final solution, I have the same problem, I make a single jar file, but still throw exception  java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.HashMap$SerializationProxy to field epic.features.BrownClusterFeaturizer.epic$features$BrownClusterFeaturizer$$clusterFeatures of type scala.collection.immutable.Map in instance of epic.features.BrownClusterFeaturizer

Who can help me, thanks a lot.

**Comment by acvogel** [comment]
@ltao80 I never got it to work and gave up. I'd be curious to hear from anyone else with a detailed solution.

**Comment by ltao80** [comment]
@acvogel  Thank you for your reply, I gave up too, I change to use Stanford NLP

**Comment by Tooa** [comment]
I'm facing the same problem (see here [1]). I've tried @JSantosP suggestion and added several dependencies to the `SparkConf`. 

```
val path = "/home/.../.../spark-fun/jars/"
    val conf = new SparkConf().setAppName("wordCount").setJars(Seq(
      path + "epic_2.10-0.3.jar",
      path + "epic-ner-en-conll_2.10-2015.1.25.jar",
      path + "nak_2.10-1.3.jar",
      path + "scala-logging-api_2.10-2.1.2.jar",
      path + "scala-logging-slf4j_2.10-2.1.2.jar",
      path + "breeze_2.10-0.11-M0.jar",
      path + "spark-assembly-1.5.2-hadoop2.6.0.jar",
      path + "spark-fun-assembly-1.0.jar"
    ))
```
Do I need the path here? I also wonder, why I should add these jars to the `SparkConf`. Using a fat jar that was generated with  `sbt assembly` should be enough, right? The project dependency tree looks like [2]. Do I really need to add all of these dependencies to the `SparkConf`?

[1] https://github.com/Tooa/spark-fun
[2] https://gist.github.com/Tooa/a2d364d7d457c64dd68f
