### ISSUE TITLE
PL parser doesn't work

### ISSUE THREAD

**Issue by woj-i** [dlwh/epic#35]
Trained parser of polish language from http://www.scalanlp.org/models/ does not work with current master branch. I tried to run:
java -Xmx6g -cp target/scala-2.11/epic-assembly-0.4-SNAPSHOT.jar epic.parser.ParseText --model epic-parser-pl-span_2.10-2014.6.3-SNAPSHOT.jar --nthreads 4 exampleArticle.txt

and I get:
Couldn't deserialize model due to exception, epic.parser.models.ParserTrainer$$anonfun$2; local class incompatible: stream classdesc serialVersionUID = 0, local class serialVersionUID = 5531977503861241212. Trying classPathLoad...
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at epic.parser.ParseText$.classPathLoad(ParseText.scala:21)
	at epic.parser.ParseText$.classPathLoad(ParseText.scala:11)
	at epic.util.ProcessTextMain$class.main(ProcessTextMain.scala:47)
	at epic.parser.ParseText$.main(ParseText.scala:11)
	at epic.parser.ParseText.main(ParseText.scala)

which says, that version of classes are not the same.

I also downloaded JAR from maven repository and there is the same error.

**Comment by woj-i** [comment]
I was able to run the model when I checked out to commit of the tag releases/v0.1

**Comment by pommedeterresautee** [comment]
Seems related to #36 and #26

**Comment by dlwh** [comment]
yeah, i havent' maintained the non-english models, sorry. Older versions
work fine.

**Comment by pommedeterresautee** [comment]
For french using maven version was ok
