### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Malkitti** [dlwh/epic#61]
[main] INFO epic.parser.models.ParserTrainer$ - Training Parser...
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
	at scala.collection.IndexedSeqLike$class.iterator(IndexedSeqLike.scala:90)
	at scala.collection.mutable.ArrayOps$ofRef.iterator(ArrayOps.scala:186)
	at epic.trees.Treebank$$anon$2.treesFromSection(Treebank.scala:125)
	at epic.trees.Treebank$$anonfun$treesFromSections$1.apply(Treebank.scala:67)
	at epic.trees.Treebank$$anonfun$treesFromSections$1.apply(Treebank.scala:67)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$21.hasNext(Iterator.scala:836)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:732)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:708)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toIndexedSeq(TraversableOnce.scala:300)
	at scala.collection.AbstractIterator.toIndexedSeq(Iterator.scala:1336)
	at epic.trees.ProcessedTreebank.transformTrees(ProcessedTreebank.scala:84)
	at epic.trees.ProcessedTreebank.devTrees$lzycompute(ProcessedTreebank.scala:73)
	at epic.trees.ProcessedTreebank.devTrees(ProcessedTreebank.scala:73)
	at epic.parser.ParserPipeline$class.trainParser(ParserPipeline.scala:88)
	at epic.parser.models.ParserTrainer$.trainParser(ParserTrainer.scala:47)
	at epic.parser.ParserPipeline$class.main(ParserPipeline.scala:107)
	at epic.parser.models.ParserTrainer$.main(ParserTrainer.scala:47)
	at epic.parser.models.ParserTrainer.main(ParserTrainer.scala)

**Comment by jeffchy** [comment]
I encountered the same problem, what's the solution?
