### ISSUE TITLE
at org.mapdb.Volume$ByteBufferVol.getLong(Volume.java:300)

### ISSUE THREAD

**Issue by Malkitti** [dlwh/epic#62]
Exception in thread "main" java.lang.NullPointerException
	at org.mapdb.Volume$ByteBufferVol.getLong(Volume.java:300)
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:112)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:100)
	at org.mapdb.StoreWAL.<init>(StoreWAL.java:46)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:582)
	at org.mapdb.DBMaker.make(DBMaker.java:556)
	at epic.util.CacheBroker$ActualCache.db$lzycompute(Cache.scala:50)
	at epic.util.CacheBroker$ActualCache.db(Cache.scala:49)
	at epic.util.CacheBroker.db(Cache.scala:38)
	at epic.util.CacheBroker$CacheMap.liftedTree1$1(Cache.scala:103)
	at epic.util.CacheBroker$CacheMap.theMap(Cache.scala:100)
	at epic.util.CacheBroker$CacheMap.getOrElseUpdate(Cache.scala:151)
	at epic.constraints.CachedChartConstraintsFactory.constraints(CachedChartConstraintsFactory.scala:31)
	at epic.parser.models.NeuralParserTrainer$$anonfun$trainParser$1.apply(NeuralParserTrainer.scala:113)
	at epic.parser.models.NeuralParserTrainer$$anonfun$trainParser$1.apply(NeuralParserTrainer.scala:113)
	at scala.collection.parallel.AugmentedIterableIterator$class.map2combiner(RemainsIterator.scala:115)
	at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1054)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1051)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:159)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:443)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinTask.doJoin(ForkJoinTask.java:341)
	at scala.concurrent.forkjoin.ForkJoinTask.join(ForkJoinTask.java:673)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask$class.sync(Tasks.scala:378)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:443)
	at scala.collection.parallel.ForkJoinTasks$class.executeAndWaitResult(Tasks.scala:426)
	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
	at scala.collection.parallel.ExecutionContextTasks$class.executeAndWaitResult(Tasks.scala:558)
	at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:80)
	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:958)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
	at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:953)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by malcolmgreaves** [comment]
What is the context here? What program did you run? What was the input data? What version of Scala and the epic library are you using?
